version: '3.8'

services:
  database:
    image: postgres:13
    restart: always
    ports:
      - ${POSTGRES_PORT_EXTERNAL}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
      - ./sql/api-rides-bd.sql:/docker-entrypoint-initdb.d/api-rides-bd.sql  

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: prueba@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"      

  api:
    build: .
    ports:
      - "3000:3000"
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - database
    



volumes:
  postgres_data: