version: '3.8'

services:
  database:
    image: postgres:13
    ports:
      - ${POSTGRES_PORT_EXTERNAL}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: